### PR TITLE
Fixes #5. Updates react-refresh and react-refresh-webpack-plugin packages.

### LINKED ISSUE #5: window not defined error when web workers are used.
image

Tried setting `output.globalObject: this` and `output.globalObject: self`. But, no luck.

I am using [workerize-loader](https://github.com/developit/workerize-loader) for workers.

### PR DESCRIPTION
**Pull request by saisandeepvaddi**

### CODE REVIEW

**Comment by esetnik** [comment]
Thanks for this, but I prefer to just wait until https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/45 is fixed. Then we can do a version bump without requiring users to install `webpack-hot-middleware`.

**Comment by saisandeepvaddi** [comment]
Yeah that's probably better.

**Comment by madiodio** [comment]
Hey @esetnik, sounds like https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/45 has been fixed and closed for a while now. 

Also, [a new version](https://github.com/pmmmwh/react-refresh-webpack-plugin/releases/tag/v0.3.0) of react-refresh-webpack-plugin has just been released which deprecates `disableRefreshCheck` and fixes #3 hopefully.

So maybe this PR should also be updated or superseded by a new one ? cc @saisandeepvaddi

**Comment by esetnik** [comment]
@madiodio I will work on integration the new version and make a release ASAP.

**Comment by cezarneaga** [comment]
don't mean to push, do you need a fresh PR on this to update to latest deps and rework readme? would really need the new version, but happy to contribute! thanks,
Cezar

**Comment by esetnik** [comment]
> So maybe this PR should also be updated or superseded by a new one ? cc @saisandeepvaddi

> don't mean to push, do you need a fresh PR on this to update to latest deps and rework readme? would really need the new version, but happy to contribute! thanks,
Cezar

@cezarneaga @saisandeepvaddi @madiodio I released v1.0.4. Can you test it out and let me know if it's working well for you?

**Comment by madiodio** [comment]
@esetnik Just tested it but I'm running in this error

```
Failed to compile.

multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry.js .
```

I've tried deleting `node_modules` and `yarn.lock` but still the same issue.

Besides I believe `1.0.4` could have been a breaking or even major release because running it while still having disabled `disableRefreshCheck` will throw an error. What do you think ?

**Comment by esetnik** [comment]
> @esetnik Just tested it but I'm running in this error
> 
> ```
> Failed to compile.
> 
> multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry.js .
> ```
> 
> I've tried deleting `node_modules` and `yarn.lock` but still the same issue.
> 
> Besides I believe `1.0.4` could have been a breaking or even major release because running it while still having disabled `disableRefreshCheck` will throw an error. What do you think ?

Good point. Although this flag is only removed by react-refresh-webpack-plugin and not supposed to be used anyway so it’s a bit strange to bump major for that. I’m hesitant to do anything here because next version of create-react-app will ship with react-refresh support built-in and this plugin won’t be necessary anymore. I’m not sure how to reproduce the error you’re having but if you open a new issue with sample project I can take a look.

**Comment by madiodio** [comment]
@esetnik Yeah it's definitely weird. Well you're right since this lib won't be necessary very soon I just switched to using directly `@pmmmwh/react-refresh-webpack-plugin` following this example https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/master/examples/create-react-app and it's working well. 

Thanks.

**Comment by esetnik** [comment]
> @esetnik Yeah it's definitely weird. Well you're right since this lib won't be necessary very soon I just switched to using directly `@pmmmwh/react-refresh-webpack-plugin` following this example https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/master/examples/create-react-app and it's working well.
> 
> Thanks.

The example you provided is exactly what this plugin does. But the example is out of date and has issues so you won’t get as much benefit as using this plugin until the official release.

**Comment by cezarneaga** [comment]
i get the same error as @madiodio 
```
multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/ErrorOverlayEntry.js?sockHost=our.custom.domain.com&sockPort=4200 .
Module not found: Can't resolve '/Volumes/root/where/CRA/isLocated' in '/Volumes/root/where/CRA/isLocated' 
```
this is weird.

**Pull request closed without merging**
